######################################################################################
#This file is generated by 'CPT case create automation' , please don't edit manually#
######################################################################################
python bp_v2.py --bundle 2022.0901 -G '{"dr": "FALSE", "datacenter": "fra", "cl_opstat": "PROVISIONING", "roles": "praccn", "superpod": "NONE", "templateid": "praimage", "clusters": "PRA", "maxgroupsize": 0, "grouping": "all"}' -v --dowork None --gsize 0 --dowork None
python gus_cases_vault.py -T change --cstatus approved -f templates/bundle-patch.json --inst PRA --infra "Primary" -s "2022.0901/2022.0901 Patch Bundle: PRACCN  FRA PRA PROD[PROVISIONING] all" -k templates/6u6-plan.json -l output/praccn_fra_NONE_PRA_PROD_summarylist.txt -D FRA -i output/praccn_fra_NONE_PRA_PROD_plan_implementation.txt -r praccn --sp NONE
