#!/bin/bash
###################################################
# Package script for Strata which generates an RPM. #
###################################################
set -e
echo "----- Start CPT Tools TnRP package script -----"

# required argument; defines the version number for the artifact
VERSION="1.0"

# required argument; rpm should be unique, generate a timestamp
ITERATION=$(date +"%Y%m%d%H%M%S")

echo "pwd: $(pwd)"
echo "version: $VERSION"
echo "iteration: $ITERATION"

# build the package by running the build script
./build.sh -i $ITERATION -v $VERSION
