#!/bin/bash
##############################################
# unit_script
# mgaddy@salesforce.com
# unit test script for cpt that will be 
# called by the pipeline
#
##############################################
set -e

# Currently unit test will be perform by CPT therefore
# this script just need exit with success. 

exit 0
